export enum Permissions {
    GET_ALL_PROJECT = 'PROJECT.GETALL',
    GET_PROJECT_BY_ID ='PROJECT.GETBYID',
    CREATE_PROJECT = 'PROJECT.CREATE',    
    UPDATE_PROJECT = 'PROJECT.UPDATE',   
    ARCHIVE_PROJECT = 'PROJECT.ARCHIVE', 
    VIEW_PROJECT='PROJECT.VIEW',   

    CREATE_USER = 'USER.CREATE',
    INACTIVE_USER = 'USER.INACTIVE',
    UPDATE_USER = 'USER.UPDATE',
    ARCHIVE_USER = 'USER.ARCHIVE',
    GET_ALL_USER = 'USER.GETALL',
    GET_USER_BY_ID ='USER.GETBYID',  

    CREATE_CONTACT = 'CONTACT.CREATE',   
    UPDATE_CONTACT = 'CONTACT.UPDATE',
    ARCHIVE_CONTACT = 'CONTACT.ARCHIVE',
    GET_ALL_CONTACT = 'CONTACT.GETALL',
    GET_CONTACT_BY_ID = 'CONTACT.GETBYID',
    VIEW_CONTACT='CONTACT.VIEW',

    CREATE_INDUCTION = 'INDUCTION.CREATE',
    UPDATE_INDUCTION = 'INDUCTION.UPDATE',
    GET_ALL_INDUCTION = 'INDUCTION.GETALL',
    GET_INDUCTION_BY_ID = 'INDUCTION.GETBYID',
    VIEW_INDUCTION='INDUCTION.VIEW',
    PRINT_INDUCTION='INDUCTION.PRINT',
    APPROVE_INDUCTION='INDUCTION.APPROVE',

    CREATE_WEEKLY_INSPECTION='WEEKLYINSPECTION.CREATE',
    UPDATE_WEEKLY_INSPECTION='WEEKLYINSPECTION.UPDATE',
    VIEW_WEEKLY_INSPECTION='WEEKLYINSPECTION.VIEW',
    ARCHIVE_WEEKLY_INSPECTION='WEEKLYINSPECTION.ARCHIVE',

    VIEW_TIMESHEET = 'TIMESHEET.VIEW',
    PRINT_TIMESHEET='TIMESHEET.PRINT'

 
  }